CYK: CYK.class
	java Production.class FileManager.class CYK.class $(filter-out $@,$(MAKECMDGOALS))

CYK.class: Production.java FileManager.java CYK.java
	javac Production.java FileManager.java CYK.java
